---
- name: restart postgresql
  sudo: yes
  service: name=postgresql state=restarted

- name: stop postgresql
  sudo: yes
  service: name=postgresql state=stopped

- name: reload postgresql
  sudo: yes
  service: name=postgresql state=reloaded